import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Footer from "@/components/common/footer";
import { Header } from "@/components/common/header";
import { TemporaryCartCleanup } from "@/components/common/temporary-cart-cleanup";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/providers/auth-provider";
import ReactQueryProvider from "@/providers/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
        suppressHydrationWarning
      >
        <AuthProvider>
          <ReactQueryProvider>
            <Header />
            <div className="flex-1">
              <TemporaryCartCleanup />
              {children}
            </div>
          </ReactQueryProvider>
        </AuthProvider>
        <Toaster position="top-center" />
        <Footer />
      </body>
    </html>
  );
}
